# Setup
title:               Hybrid-Konferenz Vision
tagline:             'Ideensammlung für hybride Veranstaltungen'
description:         'Aufgrund der Corona Pandemie werden viele Konferenzen, wie auch die JavaLand 2021, noch nicht wieder gewohnt stattfinden können. Deshalb machen wir uns Gedanken, wie eine hybride Veranstaltung aussehen und vor allem für alle Beteiligten attraktiv sein könnte. Darüber wollen wir hier berichten und freuen uns über Feedback. Diskussionen bitte über den <a href="https://jvm-german.slack.com/archives/C4H2WGBL4">#javaland</a> Channel des JVM-German Slack Workspace (<a href="https://slackin-jvm-german.herokuapp.com/">hier kostenlos registrieren</a>).'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty
incremental:         true
github:
  repo:              https://github.com/cyberlandconf/blog
ijug:
  web:              https://www.ijug.eu/
  impressum:        https://www.ijug.eu/de/impressum/

# About/contact
author:
  - name:            Tobias Frech
    url:             https://twitter.com/TobiasFrech
    email:           tobias@frech.info
  - name:            Sandra Parsick
    url:             https://twitter.com/SandraParsick
    email:           mail@sandra-parsick.de
  - name:            Falk Sippach
    url:             https://twitter.com/sippsack
    email:           falk@jug-da.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
